# SPDX-License-Identifier: LGPL-2.1-or-later

# Requires desktop profile.

[Content]
Packages=
        baobab
        papers
        gdm
        gnome-backgrounds
        gnome-calculator
        gnome-calendar
        gnome-clocks
        gnome-control-center
        gnome-disk-utility
        gnome-keyring
        gnome-logs
        gnome-menus
        gnome-music
        gnome-session
        gnome-settings-daemon
        gnome-shell
        gnome-software
        gnome-system-monitor
        gnome-console
        gnome-text-editor
        ibus
        nautilus
        tecla
        loupe
        xdg-desktop-portal-gnome
        xdg-desktop-portal-gtk
        xdg-user-dirs-gtk
